[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Jeff Hutchison <jeff@jeffhutchison.com>"]
edition = "2018"

[dependencies]
num = "0.1.42"
image = "0.21.0"
crossbeam = "0.2.12"
num_cpus = "1.10.0"
